<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CursoDotNet.Domain\CursoDotNet.Domain.csproj" />
    
    <ProjectReference Include="..\CursoDotNet.Persistence\CursoDotNet.Persistence.csproj" />

  </ItemGroup>

</Project>
